---
stages:
- test-infra
- build-image

run-molecule:
  image: automium/molecule:2.22-bionic
  stage: test-infra
  script:
  - bash cicd/test.sh
  only:
  - refactoring
  tags:
  - automium-infra-test

build-image:
  image: automium/buildenv:bionic
  stage: build-image
  script:
  - bash cicd/build.sh
  only:
  - refactoring
  when: manual
