---

language: python
python: 2.7
sudo: required

services:
  - docker

stages:
  - unittest
  - build
  - deploy
  - test
  - release

jobs:
  include:
    - stage: unittest
      script: 'if [ ! "$TRAVIS_TAG" ]; then bash cicd/unittest.sh; fi'
    - stage: build
      script: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ ! "$TRAVIS_TAG" ]; then bash cicd/build.sh; fi'
    - stage: build
      script: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ ! "$TRAVIS_TAG" ]; then bash cicd/container.sh; fi'
#    - stage: deploy
#      script: bash cicd/provisioner.sh openstack
#    - stage: release
#      script: bash cicd/release.sh
#      if: branch = master
