---
version: '3'
services:
  molecule:
    image: automium/molecule-ci:2.22
    volumes:
      - .:/root/src/service-kubernetes
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /root/src/service-kubernetes
