---
- name: configure others | create token from remote master node

  - name: configure-bootstrap | bootstrap first master
    command: >-
      kubeadm token create --print-join-command
    register: kubeadm_upload_cert