---
- name: configure | ssh config
  template:
    src: ssh_config
    dest: /root/.ssh/config
  when: testmode != "true"

- name: configure | render cloud configurations
  template:
    src: "templates/provider/{{ cloud_provider }}/cloud.conf.j2"
    dest: /etc/kubernetes/cloud.conf
    owner: root
    group: root
    mode: 0600
  when: provider != "none"