---
- name: image | add apt-transport-https
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: image | add Kubernetes repository GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: image | add Kubernetes repository in APT
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    
- name: image | install kubernetes binaries
  apt:
    name: ["kubeadm={{ k8s_version }}-00", "kubelet={{ k8s_version }}-00", "kubectl={{ k8s_version }}-00", "glusterfs-client", "python-pip"]
    state: present    

- name: image | install consul.py
  pip:
    name: "{{ item }}"
  with_items:
    - python-consul==1.0.0
    - netaddr

- name: image | enable kubelet service
  service:
    name: kubelet
    enabled: yes
    
- name: image | create Kubernetes configuration directory
  file:
    path: /etc/kubernetes
    state: directory
    recurse: yes
    owner: root
    group: root

- name: image | add module dm_thin_pool for thin volumes provisioning
  modprobe:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ kernel_modules }}"
  when: testmode != "true"

- name: image | add module dm_thin_pool for thin volumes provisioning
  lineinfile:
    path: /etc/modules
    state: present
    create: yes
    line: '{{ item }}'
  with_items: "{{ kernel_modules }}"
  when: testmode != "true"

- name: image | create roles requirement
  copy:
    content: |
      - src: https://github.com/entercloudsuite/ansible-consul.git
        version: 2.0.2
        name: entercloudsuite.consul
      - src: https://github.com/entercloudsuite/ansible-docker
        version: 2.0.4
        name: entercloudsuite.docker
    dest: /usr/src/cloud/requirement.yml

- name: image | ensure roles directory exist
  file:
    path: /usr/src/cloud/roles
    state: directory

- name: image | download roles
  shell: |
    source venv/bin/activate
    ansible-galaxy install -r requirement.yml -p roles
  args:
    chdir: /usr/src/cloud
    executable: /bin/bash

- name: image | set docker cgroup driver for test mode
  set_fact:
    docker_cgroup_driver: cgroupfs
  when: testmode == "true"

- name: image | install consul service
  include_role:
    name: entercloudsuite.consul
    public: yes
  vars:
    consul_version: 1.4.4
    configure: false
    install: true
    consul_service_status: "stopped"
- name: image | import docker role
  include_role:
    name: entercloudsuite.docker
    public: yes

- name: image | restart Docker
  service:
    name: docker 
    state: started

- name: image | download Kubernetes system containers
  command: kubeadm config images pull

- name: image | stop Docker
  service:
    name: docker 
    state: stopped

- name: image | remove useless dependecy
  apt:
    name: ["unattended-upgrades"]
    state: absent
