---

- name: image | add apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: image | add Kubernetes repository GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: image | add Kubernetes repository in APT
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: image | install kubernetes binaries
  apt:
    name: ["kubeadm={{ k8s_version }}-00", "kubelet={{ k8s_version }}-00", "kubectl={{ k8s_version }}-00", "glusterfs-client", "python-pip"]
    state: present    

- name: image | install consul.py
  pip:
    name: "{{ item }}"
  with_items:
    - python-consul==1.0.0
    - netaddr
  tags: image

- name: image | enable kubelet service
  service:
    name: kubelet
    enabled: yes
    
- name: image | create Kubernetes configuration directory
  file:
    path: /etc/kubernetes
    state: directory
    recurse: yes
    owner: root
    group: root

- name: image | add module dm_thin_pool for thin volumes provisioning
  modprobe:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ kernel_modules }}"
  when: testmode != "true"

- name: image | add module dm_thin_pool for thin volumes provisioning
  lineinfile:
    path: /etc/modules
    state: present
    create: yes
    line: '{{ item }}'
  with_items: "{{ kernel_modules }}"
  when: testmode != "true"

#DOTO Move to docker installation roles
- name: Docker | move docker native cgroupdriver to systemd
  copy:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json

- name: image | download Kubernetes system containers
  command: kubeadm config images pull

