---
- name: image | set kube version
  set_fact:
    k8s_version: 1.15.3
    calico_pool_cidr: 10.233.64.0/20

- name: image | install kubernetes binary
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - kubeadm={{ k8s_version }}-00
    - kubelet={{ k8s_version }}-00
    - kubectl={{ k8s_version }}-00

- name: image | enable kubelet
  service:
    name: kubelet
    state: enabled
    
- name: image | install kubernetes binary
  file:
    path: /etc/kubernetes
    state: directory
    recurse: yes
    owner: root
    group: root