---
- name: Add an Apt signing key to a specific keyring file
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: image | install kubernetes binary
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - kubeadm={{ k8s_version }}-00
    - kubelet={{ k8s_version }}-00
    - kubectl={{ k8s_version }}-00
    - glusterfs-client
    - python-pip

- name: image | install consul.py
  pip:
    name: "{{ item }}"
  with_items:
    - python-consul==1.0.0
    - netaddr
  tags: image


- name: image | enable kubelet
  service:
    name: kubelet
    enabled: yes
    
- name: image | install kubernetes binary
  file:
    path: /etc/kubernetes
    state: directory
    recurse: yes
    owner: root
    group: root

- name: image | Add module dm_thin_pool for thin volumes provisioning
  modprobe:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ kernel_modules }}"

- name: image | Add module dm_thin_pool for thin volumes provisioning
  lineinfile:
    path: /etc/modules
    state: present
    create: yes
    line: '{{ item }}'
  with_items: "{{ kernel_modules }}"

#DOTO Move to docker installation roles
- name: Docker | move docker native cgroupdriver to systemd
  copy:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json

- name: image | Download docker container
  command: kubeadm config images pull

- name: image | deploy consul check kubernetes-check-node
  copy:
    src: scripts/kubernetes-check-node.sh
    dest: /opt/consul/bin/kubernetes-check-node
    owner: consul
    group: consul
    mode: 0700

- name: consul | deploy consul check etcd-consul-check
  copy:
    src: scripts/etcd-consul-check.py
    dest: /opt/consul/bin/etcd-consul-check
    owner: consul
    group: consul
    mode: 0700