---
- import_tasks: all/get_vars.yaml
  tags: image

- import_tasks: image.yml
  tags: image

- import_tasks: all/consul.yml

- import_tasks: all/configure.yml

- import_tasks: "{{ init_role }}/configure-{{ init_role }}.yml"

- import_tasks: all/post_conf.yaml
