- name: post conf | deploy script for create consul kube_config
  copy:
    src: scripts/consul_kubectl.sh
    dest: /tmp/consul_kubectl.sh
    owner: root
    group: root
    mode: 0700

- name: post conf | create kubeconfig for consul
  command: /tmp/consul_kubectl.sh

- name: post conf | restart consul for reload check
  service:
    name: consul
    state: restarted
