---

- name: postconf filebeat | show vars
  debug:
    var: filebeat_conf_string

- name: postconf filebeat | filter filebeat_conf
  set_fact:
    filebeat_conf: "{{ filebeat_conf_string | from_yaml }}"

- name: postconf filebeat | show normalized
  debug:
    var: filebeat_conf

- name: postconf filebeat | Exec filebeat roles
  include_role:
    name: entercloudsuite.filebeat
    public: yes
