---

- name: post-conf-falco | reduce noise in falco audit
  package: name={{ item }}
  with_items:
    - ubuntu-release-upgrader-core
    - update-notifier-common

- name: post-conf-falco | reduce noise in falco audit
  file: path={{ item }} state=absent
  with_items:
    - /etc/cron.daily/dpkg
    - /etc/cron.daily/man-db
    - /etc/cron.daily/mlocate
    - /etc/cron.daily/ubuntu-advantage-tools
    - /etc/cron.daily/apt-compat
    - /etc/cron.weekly/update-notifier-common
    - /etc/cron.weekly/man-db
    - /etc/update-motd.d
    - /var/run/motd.dynamic

- name: post-conf-falco | install kernel headers
  apt:
    name: "linux-headers-{{ ansible_kernel }}"
    state: present
  tags: image

- name: post-conf-falco | add draios key
  apt_key:
    url: https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public
    state: present
  register: pkg_result
  until: pkg_result is success
  tags: image

- name: install draios apt source
  get_url:
    url: http://download.draios.com/stable/deb/draios.list
    dest: /etc/apt/sources.list.d/draios.list
    mode: 0444
    checksum: 'sha256:e9e2ed7d6f02607d855cfe14ef3d37eb13bdb75cecb735b93f12c9af6693185f'
  tags: image

- name: post-conf-falco | install falco
  apt:
    name: falco
    state: present
    update_cache: yes
  register: pkg_result
  until: pkg_result is success
  tags: image

- name: post-conf-falco | stop falco
  service:
    name: falco
    state: stopped

- name: post-conf-falco | copy falco conf
  copy:
    src: falco/falco.conf.yaml
    dest: /etc/falco/falco.yaml
    mode: 0644

- name: post-conf-falco | copy falco checks
  copy:
    src: falco/falco_rules.yaml
    dest: /etc/falco/falco_rules.yaml
    mode: 0644

- name: post-conf-falco | copy telegram notifier script
  template:
    src: falco/tg-notify.sh.j2
    dest: /etc/falco/tg-notify.sh
    mode: 0755

- name: post-conf-falco | start falco
  service:
    name: falco
    state: restarted
