---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    molecule_file: "{{ lookup('env','MOLECULE_FILE') }}"
    molecule_scenario_directory: "{{ lookup('env','MOLECULE_SCENARIO_DIRECTORY') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"
  tasks:
    - name: Create Consul instance
      docker_container:
        name: "consul"
        hostname: "automium-agent"
        image: consul
        command: "agent -server -ui -bootstrap -data-dir=/tmp/data -bind=0.0.0.0 -client=0.0.0.0 -dns-port=53 -datacenter=automium -recursor=8.8.8.8 -encrypt='A2+WhqBtZjsA5tLlpOOmBXoTprRFMWnc+N5beexyZiM='"
        env:
          CONSUL_ALLOW_PRIVILEGED_PORTS: ""
        state: started
        recreate: no
      register: consul_container_data
    - name: Create local volumes for instances data
      docker_volume:
        name: "{{ item.dataVolume }}"
        driver: local
        state: present
      with_items: "{{ molecule_yml.platforms }}"
    - name: Create molecule instance(s)
      docker_container:
        name: "{{ item.name }}"
        hostname: "{{ item.name }}"
        image: automium/ci-testenv:bionic
        privileged: True
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:ro
          - /lib/modules:/lib/modules:ro
          - /boot:/boot:ro
          - "{{ item.dataVolume }}:/var/lib/docker"
        tmpfs:
          - /run
          - /run/lock
        dns_servers:
          - "{{ consul_container_data.ansible_facts.docker_container.NetworkSettings.IPAddress }}"
        state: started
        recreate: no
        log_driver: none
      with_items: "{{ molecule_yml.platforms }}"
