---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance-1
provisioner:
  name: ansible
  options:
    diff: True
    v: True
    e: test_env=true
  playbooks:
    create: create.yml
    prepare: prepare.yml
    destroy: destroy.yml
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - syntax
verifier:
  name: goss
