---
- name: test role wrapper
  hosts: all
  gather_facts: False
  tasks:
  - name: launch the test playbook on the remote instance 
    command: ansible-playbook -i 127.0.0.1 --extra-vars 'testmode="true" cluster_name="testcluster" identity="testcluster-ci" image="kubernetes-ci-test" provider="none"' /usr/src/cloud/roles/service-kubernetes/molecule/default/playbook.test.yml
    args:
       chdir: /usr/src/cloud
    environment:
      ANSIBLE_ROLES_PATH: ':/tmp/:/usr/src/cloud/roles'
      CONSUL_ENCRYPT: 'A2+WhqBtZjsA5tLlpOOmBXoTprRFMWnc+N5beexyZiM='